---

# install VisiCut

- name: install VisiCut dependencies
  package:
    name: '{{ pkg_names[item]|default(item) }}'
    state: present
  with_items:
    - openjdk-8-jre
    - potrace
  tags:
    - visicut-packages
    - packages

- name: enable Java Font antialiasing
  template:
    src: etc/profile.d/java_antialiasing.sh
    dest: /etc/profile.d/java_antialiasing.sh
    mode: 'u=rwX,g=rX,o=rX'
  tags:
   - visicut-packages

- set_fact:
    visicut_version: 1.8-31-g2d3f6b97

- name: test if visicut is up-to-date
  shell: 'PATH=/usr/local/bin:$PATH visicut --version 2>&1 | fgrep -q {{visicut_version}} && echo true || echo false'
  register: visicut_up_to_date_tmp
  ignore_errors: yes

- set_fact:
    visicut_up_to_date='{{ visicut_up_to_date_tmp.stdout | trim | bool }}'

- debug:
    var: visicut_up_to_date
- debug:
    var: visicut_up_to_date_tmp.stdout

# may be slow. Download server is weird sometimes.
# TODO: download latest version
- name: download VisiCut deb package (Debian, Ubuntu)
  apt:
    deb: 'https://download.visicut.org/files/master/Debian-Ubuntu-Mint/visicut_{{visicut_version}}-1_all.deb'
    allow_unauthenticated: yes
  when: ansible_distribution in ["Debian", "Ubuntu"] and not visicut_up_to_date
  tags:
    - visicut-install

# may be slow. Download server is weird sometimes.
# TODO: always download the latest version
- name: download and extract VisiCut zip archive (Fedora)
  unarchive:
    src: 'https://download.visicut.org/files/master/All/VisiCut-{{visicut_version}}.zip'
    dest: /opt/
    remote_src: true
    owner: root
    group: root
    mode: 'u=rwX,g=rX,o=rX'
  when: ansible_distribution == 'Fedora' and not visicut_up_to_date
  tags:
    - visicut-install
    - packages

- name: symlink VisiCut scripts (Fedora)
  file:
    src: '/opt/visicut/{{ item.src }}'
    dest: '{{ item.dst }}'
    state: link
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  when: ansible_distribution == 'Fedora'
  with_items:
    - src: VisiCut.Linux
      dst: /usr/local/bin/visicut
    - src: VisiCut.Linux
      dst: /usr/local/bin/VisiCut.Linux
    - src: inkscape_extension/daemonize.py
      dst: /usr/share/inkscape/extensions/daemonize.py
    - src: inkscape_extension/visicut_export.inx
      dst: /usr/share/inkscape/extensions/visicut_export.inx
    - src: inkscape_extension/visicut_export.py
      dst: /usr/share/inkscape/extensions/visicut_export.py
    - src: inkscape_extension/visicut_export_replace.inx
      dst: /usr/share/inkscape/extensions/visicut_export_replace.inx
  tags:
    - visicut-install
    - packages

# see VisiCut debian package
- name: run VisiCut post install script (Fedora)
  shell: >
    xdg-icon-resource install --context mimetypes --size 128 /opt/visicut/examples/Basic/visicut-icon.png application-x-plf &&
    xdg-icon-resource install --context mimetypes --size 128 /opt/visicut/examples/Basic/visicut-icon.png application-x-ls &&

    xdg-mime install /opt/visicut/plf-mime.xml &&
    xdg-mime install /opt/visicut/ls-mime.xml &&

    update-desktop-database -q &&
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor &&

    chmod +x /opt/visicut/VisiCut.Linux
  when: ansible_distribution == 'Fedora'
  tags:
    - visicut-install
    - packages
