---

- name: workstation deployment
  hosts: workstations
  vars_files:
    - group_vars/all.yml
    - 'group_vars/{{ ansible_distribution }}.yml'
  roles:
    - role: common
      tags: common
    - role: users
      tags: users
    - role: software
      tags: software
    - role: fablab-share
      tags: fablab-share
