---

- name: workstation deployment
  hosts: workstations
  vars:
    - group_vars/all.yml
    - 'group_vars/{{ ansible_distribution }}.yml'
  roles:
    - role: common
      tags: common
    - role: fablab-share
      tags: fablab-share
    - role: users
      tags: users
