---

# install and remove packages

# dnf module would fail the first time
- name: install deps for ansible modules
  command: dnf install -y libselinux-python3
  args:
    creates: /usr/lib64/python3.5/site-packages/selinux

- name: install rpmfusion
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version|int}}.noarch.rpm
    state: present

# This currently crashes: https://github.com/ansible/ansible/issues/20326
# - name: trust rpmfusion key
#   rpm_key:
#     state: present
#     key: https://rpmfusion.org/keys?action=AttachFile&do=view&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ansible_distribution_major_version|int}}

- name: remove unneded packages
  dnf:
    name={{ item }}
    state=absent
  with_items:
  - akonadi
  - kmail
  - kaddressbook
  - kdepim-common
  - anaconda-gui
  - plasma-discover
  - apper
  - telepathy-qt5
  - calligra-core
  - konqueror
  - kde-connect
  - fedora-bookmarks
  - qupzilla
  - qt5-qdbusviewer

# needs too long
# - name: upgrade all packages
#   dnf:
#     name: "*"
#     state: latest

- name: install basic packages
  dnf:
    name={{ item }}
    state=present
  with_items:
  - htop
  - ncdu
  - tree
  - iftop
  - vim
  - tmux
  - firefox
  - inkscape
  - gimp
  - kicad
  - libreoffice
  - vlc
  - remmina
  - git
