---

- name: install network manager module dependencies (Fedora)
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - dbus-python
    - NetworkManager-glib
    - python-gobject
  when: ansible_distribution == 'Fedora'

- name: install network manager module dependencies (Debian)
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - gir1.2-networkmanager-1.0
    # the following may be unnecessary:
    - python-dbus
    - libnm-glib4
    - libnm-gtk0
    - python-gobject
  when: ansible_distribution in ['Debian', 'Ubuntu']

# TODO https://github.com/ansible/ansible/issues/34012
- name: configure lasercutter lan
  nmcli:
    state: present
    conn_name: 'Lasercutter'
    autoconnect: false
    type: ethernet
    ip4: '10.188.64.42/24'
    # Lasercutter has 10.188.64.37. See lasercutter.lab.fablab.uni-erlangen.de.

...
