- name: Paketquellen non-free
  command: apt-add-repository "deb http://http.debian.net/debian/ stretch main non-free contrib"

- name: Firmware non-free
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - firmware-linux-nonfree
    - firmware-realtek
    - firmware-iwlwifi
    - firmware-atheros
  tags:
    - basis

  
- name: Pakete
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - bash-completion
    - inkscape
    - gimp
    - task-kde-desktop
    - task-german
    - task-german-kde-desktop
    - libreoffice
    - vlc
    #- samba
    #- docker.io
  tags:
    - basis

    
- name: VisiCut Abhängigkeiten
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jre
    - potrace
  tags:
    - visicut

# kann lange dauern, der Downloadserver ist manchmal komisch.
- name: VisiCut (1/2)
  get_url:
    url: https://download.visicut.org/files/master/Debian-Ubuntu-Mint/visicut_1.8-4-gf11597ba-1_all.deb
    dest: /var/run/visicut.deb
  tags:
    - visicut

- name: VisiCut (2/2)
  command: dpkg -i /var/run/visicut.deb
  tags:
    - visicut
  
  
- name: VisiCam packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - openjdk-8-jdk
    - libopencv2.4-java
    - ant
    - git
    - v4l2ucp
    - fswebcam
  tags:
    - visicam

- name: clone VisiCam
  git:
    repo: https://github.com/t-oster/VisiCam.git
    dest: /opt/VisiCam/
    update: false  # no auto-updates via ansible
  tags:
    - visicam

- name: build VisiCam
  shell: cd /opt/VisiCam && ./lib/fetch-javacv.sh  && ant
  tags:
    - visicam

- name: clone VisiCam config
  git:
    repo: https://github.com/fau-fablab/visicam-config
    dest: /opt/visicamconfig
    update: false  # no auto-updates via ansible
  tags:
    - visicam
    
- name: symlink VisiCam config 1
  file: 
    src: /opt/visicamconfig/visicam.conf
    dest: /opt/VisiCam/visicam.conf
    state: link
  tags:
    - visicam
    
- name: symlink VisiCam config 2
  file: 
    src: /opt/visicamconfig/camera-script/
    dest: /opt/VisiCam/camera-script
    state: link
  tags:
    - visicam

- name: add VisiCam service user
  command: adduser --system visicam

- name: VisiCam permissions (rough workaround)
  file:
    path: /opt/VisiCam
    state: directory
    owner: visicam
  tags:
   - visicam

- name: VisiCam permissions (rough workaround)
  file:
    path: /opt/visicamconfig/camera-script
    state: directory
    owner: visicam
  tags:
   - visicam

   
   
- name: copy VisiCam service
  command: cp /opt/VisiCam/init-scripts/visicam.service /lib/systemd/system/
  tags:
    - visicam
  notify: restart visicam

- name: enable VisiCam service
  command: systemctl enable visicam
