---
# Handlers are run on notify <name>
###################################

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart visicam
  service:
    name: visicam
    state: restarted

- name: reboot required
  command: touch /var/run/reboot-required && echo ansible_playbook_notification >> /var/run/reboot-required.pkgs
