---

# set up the fablab user

- name: fablab user
  user:
    name: fablab
    password: "{{ 'fablab'|password_hash('sha512') }}"
    groups:
    append: true
    shell: /bin/bash

- name: add face icon
  copy:
    src: fab_cube_whitebg.svg
    dest: /home/fablab/.face.icon
    owner: fablab
    group: fablab
    mode: 'u=rw,g=rw,o=rw'

- name: fix acl for face icon
  acl:
    path: /home/fablab
    entity: sddm
    etype: user
    permissions: x
    state: present

- name: add sddm config to autologin fablab user
  template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: 0644

- name: create required directories
  file:
    path: '{{ item }}'
    state: directory
    owner: fablab
    group: fablab
  with_items:
    - /home/fablab/.config/
    - /home/fablab/.local/share/remmina/
    - /home/fablab/Schreibtisch/

- name: don't lock the screen
  template:
    src: kscreenlockerrc.j2
    dest: /home/fablab/.config/kscreenlockerrc
    owner: fablab
    group: fablab
    mode: 'u=rw,g=o='

- name: disable screen corners
  template:
    src: kwinrc.j2
    dest: /home/fablab/.config/kwinrc
    owner: fablab
    group: fablab
    mode: 'u=rw,g=o='

- name: set default samba password (if someone tries to access brain via kde tools)
  template:
    src: kioslaverc.j2
    dest: /home/fablab/.config/kioslaverc
    owner: fablab
    group: fablab
    mode: 'u=rw,g=o='

- name: disable singleclick
  template:
    src: kdeglobals.j2
    dest: /home/fablab/.config/kdeglobals
    owner: fablab
    group: fablab
    mode: 'u=rw,g=o='

- name: workaround for firefox-esr on Debian
  file:
    src: "/usr/share/applications/firefox-esr.desktop"
    dest: "/usr/share/applications/firefox.desktop"
    state: link
  when: ansible_distribution == 'Debian'

    
- name: add desktop links to desktop
  file:
    src: "/usr/share/applications/{{ item }}.desktop"
    dest: "/home/fablab/Schreibtisch/{{ item }}.desktop"
    state: link
  with_items:
    - firefox
    - inkscape
    - gimp
    - libreoffice-calc
    - libreoffice-writer
    - org.kde.konsole

- name: remove home desktop icon
  file:
    path: /home/fablab/Schreibtisch/Home.desktop
    state: absent

- name: add ws11 rdp config file
  template:
    src: ws11-rdp.remmina.j2
    dest: /home/fablab/.local/share/remmina/ws11-rdp.remmina
    owner: fablab
    group: fablab
    mode: 'u=rw,g=,o='

- name: add ws11 rdp and fablab share desktop icon
  template:
    src: "{{ item }}.desktop.j2"
    dest: "/home/fablab/Schreibtisch/{{ item }}.desktop"
    owner: fablab
    group: fablab
    mode: 'u=rw,g=r,o=r'
  with_items:
    - ws11
    - Freigabe
