---

# set up the admin user

- name: sysadmin user
  user:
    name: sysadmin
    groups: wheel,fablab
    append: yes
    shell: /bin/bash

- authorized_key:
    user: sysadmin
    key: '{{item}}'
  with_items: '{{ ssh_pubkeys.values }}'
  tags:
    - sysadmin-authorized-keys
    - ssh

- name: sudoers - passwordless sudo for 'sudo' group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD:ALL'
    # validation is run on a temporary copy before the real content is copied
    validate: 'visudo -q -c -f %s'
  tags:
    - sudoers
