---

# configure, enable and start chronyd (time synchronization deamon)

- name: configure chrony
  template:
    src=chrony.conf.j2
    dest=/etc/chrony.conf
    owner=root
    group=root
    mode=644
  notify: restart chronyd

- name: enable and start chronyd
  systemd:
    name: chronyd.service
    enabled: yes
    state: started
