---

# Common tasks: Basic dependencies of ansible, and anything which does not require later tasks.
# These MUST NOT depend on the fablab user being available, because it will be added later.


- name: Verify ansible is new enough # 2.2 is too old, 2.5 is new enough, something inbetween could also be okay
  assert:
    that: "ansible_version.full is version_compare('2.5', '>=')"

- import_tasks: packages.yml
  tags: packages

- import_tasks: sshd.yml
  tags: sshd

- import_tasks: chronyd.yml
  when: ansible_distribution == 'Fedora'
  tags:
    - ntp
    - chronyd

- import_tasks: dnf-automatic.yml
  when: ansible_distribution == 'Fedora'
  tags:
    - unattented-upgrades
    - dnf-automatic

...
