---

# install and remove packages

# dnf module would fail the first time
- name: install deps for ansible modules
  command: dnf install -y libselinux-python3
  args:
    creates: /usr/lib64/python3.6/site-packages/selinux
  when: ansible_distribution == 'Fedora'
  tags:
    - fedora-packages

- name: add fedora repository rpmfusion
  dnf:
    name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version|int}}.noarch.rpm'
    state: present
  when: ansible_distribution == 'Fedora'
  tags:
    - fedora-packages
    - fedora-repos
    - repos

- name: trust fedora repository rpmfusion gpg key
  rpm_key:
    state: present
    key: 'https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ansible_distribution_major_version|int}}'
  when: ansible_distribution == 'Fedora'
  tags:
    - fedora-packages
    - fedora-repos
    - repos

- name: add debian package sources non-free
  apt_repository:
    repo: deb http://http.debian.net/debian/ stretch main non-free contrib
    state: present
  when: ansible_distribution == 'Debian'
  tags:
    - debian-packages
    - debian-repos
    - repos

- name: remove unneded packages
  package:
    name: '{{ pkg_names[item]|default(item) }}'
    state: absent
  with_items:
    - '{{ packages.absent.all }}'
    - '{{ packages.absent[ansible_distribution] }}'
  tags:
    - packages-absent

- name: install common packages
  package:
    name: '{{ pkg_names[item]|default(item) }}'
    state: present
  with_items:
    - '{{ packages.present.all }}'
    - '{{ packages.present[ansible_distribution] }}'
  tags:
    - packages-present
